pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier/cache
      - /drone/.sbt
    volumes:
      - /tmp/cache:/cache

  build:
    image: scalaplatform/scala:2.0
    secrets: [ sonatype_user, sonatype_password, github_platform_token, pgp_password ]
    volumes:
      - /fake-scalacenter:/keys
    commands:
      - echo $SONATYPE_USER
      - echo $GITHUB_PLATFORM_TOKEN

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier/cache
      - /drone/.sbt
    volumes:
      - /tmp/cache:/cache
