pipeline:
  sftp_cache:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

  build:
    image: scalaplatform/scala:0.5
    pull: true
    volumes:
      - /platform:/keys
    commands:
      - env
      - sbt clean test sbt-platform/clean sbt-platform/test sbt-platform/publishLocal sbt-platform/scripted
      - sbt process/publishProcessAndDocs

  sftp_cache:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
