pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier
      - /drone/.sbt
      - /drone/.git
    volumes:
      - /tmp/cache:/cache

  build:
    image: scalaplatform/scala:2.0
    volumes:
      - /fake-scalacenter:/keys
    commands:
      - git log | head -n 20
      - sbt clean test sbt-platform/clean sbt-platform/test sbt-platform/publishLocal sbt-platform/scripted

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier
      - /drone/.sbt
      - /drone/.git
    volumes:
      - /tmp/cache:/cache
